name: conda-example
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.1
  - openssl=1.1.1d
  - pip=20.0.2
  - python=3.7.6
  - readline=7.0
  - setuptools=45.1.0
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
